In [15]:
import pandas as pd
import numpy as np
df = pd.read_csv('../data/raw_claims.csv')
df.head(15)

   Claim_ID Policy_Type Claim_Amount         Claim_Date
0   CLM-001        Home     33574.74         2025-02-24
1   CLM-002        Life      1654.57  February 14, 2025
2   CLM-003        Life     21849.12         2025-01-25
3   CLM-004        Life    $4,664.27   October 04, 2025
4   CLM-005        Home   $44,853.00      June 29, 2025
5   CLM-006        Auto     27753.15         2025-11-08
6   CLM-007        Life     44183.82  November 23, 2025
7   CLM-008         NaN      7745.09         19/11/2025
8   CLM-009        Life     22638.12  November 16, 2025
9   CLM-010        Home     33530.38     March 01, 2025
10  CLM-011      Health     26999.82         14/09/2025
11  CLM-012        Home     37717.49         2025-09-05
12  CLM-013         NaN          NaN      July 08, 2025
13  CLM-014        Auto     12976.01                NaN
14  CLM-015        Home      1961.37                NaN

In [16]:
df['Claim_Date'] = pd.to_datetime(df['Claim_Date'], format='mixed')
df = df.dropna(subset=['Claim_Date'])
df.head(15)

   Claim_ID Policy_Type Claim_Amount Claim_Date
0   CLM-001        Home     33574.74 2025-02-24
1   CLM-002        Life      1654.57 2025-02-14
2   CLM-003        Life     21849.12 2025-01-25
3   CLM-004        Life    $4,664.27 2025-10-04
4   CLM-005        Home   $44,853.00 2025-06-29
5   CLM-006        Auto     27753.15 2025-11-08
6   CLM-007        Life     44183.82 2025-11-23
7   CLM-008         NaN      7745.09 2025-11-19
8   CLM-009        Life     22638.12 2025-11-16
9   CLM-010        Home     33530.38 2025-03-01
10  CLM-011      Health     26999.82 2025-09-14
11  CLM-012        Home     37717.49 2025-09-05
12  CLM-013         NaN          NaN 2025-07-08
15  CLM-016        Auto     33300.31 2025-10-09
16  CLM-017      Health      5506.19 2025-05-06

In [18]:
df['Claim_Amount'] = df['Claim_Amount'].replace('[\\$,]', '', regex=True).astype(float)
df = df.dropna(subset=['Claim_Amount']) 
df['Claim_Amount'] = df['Claim_Amount'].fillna(0)
df['Claim_Amount'] =df['Claim_Amount'].apply(lambda x: f"£{x:,.2f}")
df.head(15)

   Claim_ID Policy_Type Claim_Amount Claim_Date
0   CLM-001        Home   £33,574.74 2025-02-24
1   CLM-002        Life    £1,654.57 2025-02-14
2   CLM-003        Life   £21,849.12 2025-01-25
3   CLM-004        Life    £4,664.27 2025-10-04
4   CLM-005        Home   £44,853.00 2025-06-29
5   CLM-006        Auto   £27,753.15 2025-11-08
6   CLM-007        Life   £44,183.82 2025-11-23
7   CLM-008         NaN    £7,745.09 2025-11-19
8   CLM-009        Life   £22,638.12 2025-11-16
9   CLM-010        Home   £33,530.38 2025-03-01
10  CLM-011      Health   £26,999.82 2025-09-14
11  CLM-012        Home   £37,717.49 2025-09-05
15  CLM-016        Auto   £33,300.31 2025-10-09
16  CLM-017      Health    £5,506.19 2025-05-06
18  CLM-019        Auto   £13,665.28 2025-04-14

In [28]:
df= df.dropna(subset=['Policy_Type'])
df = df.sort_values(by='Policy_Type', ascending=True)
df = df.reset_index(drop=True)
df.head(15)

   Claim_ID Policy_Type Claim_Amount Claim_Date
0   CLM-207        Auto   £21,296.21 2025-11-11
1   CLM-219        Auto   £19,028.55 2025-07-02
2   CLM-220        Auto   £15,368.32 2025-07-23
3   CLM-221        Auto    £3,004.00 2025-03-28
4   CLM-485        Auto   £28,660.83 2025-04-28
5   CLM-483        Auto    £5,963.37 2025-11-06
6   CLM-016        Auto   £33,300.31 2025-10-09
7   CLM-482        Auto   £30,196.35 2025-01-21
8   CLM-481        Auto   £10,628.78 2025-01-15
9   CLM-448        Auto   £45,563.32 2025-10-23
10  CLM-193        Auto   £18,511.82 2025-01-01
11  CLM-478        Auto   £10,647.09 2025-02-15
12  CLM-023        Auto   £26,959.60 2025-10-23
13  CLM-224        Auto   £29,523.98 2025-10-28
14  CLM-028        Auto   £42,063.34 2025-01-27